### ISSUE TITLE
deletePolicy failes with UserVaultDoesNotExist

### ISSUE THREAD

**Issue by ahoehn** [ioloapp/iolo#8]
remove_policy failes from frontend:

errorMapper.ts:3 error UserVaultDoesNotExist
    at mapError (http://localhost:8080/index.js:107359:19)
    at IoloService.deletePolicy (http://localhost:8080/index.js:106756:75)
    at async http://localhost:8080/index.js:105521:9

**Comment by peterfust** [comment]
fixed and updated to new storable mechanism
